#!/usr/bin/env sh

# If bin directory is modified
git diff --cached --name-only | if grep --quiet \\.rb$; then
  changed_files=`git diff --cached --name-only --diff-filter=ACMR | grep -e "\.rb$" | paste -s -`
  lang/ruby/bin/rubocop -a --fail-level autocorrect $changed_files
fi
