inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - lang/**/*
    - emscriten/**/*
    - depends/**/*

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/BlockLength:
  Max: 60

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 60

Metrics/LineLength:
  Max: 160

Metrics/PerceivedComplexity:
  Max: 8

Style/Documentation:
  Enabled: false
