inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - emsdk/**/*
    - depends/**/*

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 60

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 60

Metrics/LineLength:
  Max: 160

Metrics/PerceivedComplexity:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 7
